version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"

    restart: unless-stopped
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=:${USER}
      - POSTGRES_PASSWORD=:${PASSWORD}
      - POSTGRES_DB=:${DATABASE}
    volumes:
        - ./postgresql/data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "80:80"
    depends_on:
      - db

  api:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    ports:
      - "8080:8080"

    restart: unless-stopped

    volumes:
      - /app/node_modules
      - ./service/config:/app/config
      - ./service/src:/app/src
 


