FROM node:16-alpine3.15
#By default create-react-app sets port to 3000 when you start react app, but I configured to run ui on 8080 (just personal preference) instead of 3000.

EXPOSE 8080 

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./

## install only the packages defined in the package-lock.json (faster than the normal npm install)
RUN npm install typescript -g 
RUN npm install ts-node    -g 
RUN npm install nodemon -g
RUN npm install

COPY . .
RUN tsc 

# Run 'npm run dev' when the container starts.
 
CMD ["npm","start"]